name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build libraries
      run: make

    - name: Run tests
      run: make test

    - name: Upload libcapi.so artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: libcapi-artifact
        path: libcapi.so
